[package]
name = "crudrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0"
futures-util= "0.3"
mongodb = "2.2"
bson = "2.7.0"
serde = "1.0"
serde_derive="1.0"
